const news = [{<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Bel Air Sour is near...can you feel it? Find it here: <a href="https://t.co/vjfB1CbG7w">https://t.co/vjfB1CbG7w</a> <a href="https://t.co/RIyjNIzMrk">pic.twitter.com/RIyjNIzMrk</a></p>&mdash; The Brooklyn Brewery (@BrooklynBrewery) <a href="https://twitter.com/BrooklynBrewery/status/822534725046771713">January 20, 2017</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>}, {<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Early morning label work to get federal approvals.. Excited for this beer, even though it hasn&#39;t… <a href="https://t.co/IsXgJIUu3B">https://t.co/IsXgJIUu3B</a></p>&mdash; Departed Soles Beer (@DepartedSoles) <a href="https://twitter.com/DepartedSoles/status/823215006212902912">January 22, 2017</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>}, {<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Global Warmer will be rolling out on shelves within the next week...🌎🔥 <a href="https://twitter.com/hashtag/GlobalWarmer?src=hash">#GlobalWarmer</a> <a href="https://t.co/K6v7LO9l8F">pic.twitter.com/K6v7LO9l8F</a></p>&mdash; Sixpoint (@sixpoint) <a href="https://twitter.com/sixpoint/status/798544956109586432">November 15, 2016</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>}, {<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Nelson IPA makes it&#39;s return this Saturday with a new friend, Mosaic + Motueka Imperial IPA.… <a href="https://t.co/TcSelrtfev">https://t.co/TcSelrtfev</a></p>&mdash; OtherHalfBrewing (@OtherHalfNYC) <a href="https://twitter.com/OtherHalfNYC/status/821761864023547904">January 18, 2017</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>}, {<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Closing early tonight at 7pm for a private event, but opening early too. Doors open at 3pm. <a href="https://t.co/DIa8yS1GF7">pic.twitter.com/DIa8yS1GF7</a></p>&mdash; Strong Rope Brewery (@StrongRopeBrew) <a href="https://twitter.com/StrongRopeBrew/status/821778798605639682">January 18, 2017</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>}, {<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Gonna be another killer show tonight! <a href="https://t.co/FHJqRqyTtL">https://t.co/FHJqRqyTtL</a></p>&mdash; Threes Brewing (@ThreesBrewing) <a href="https://twitter.com/ThreesBrewing/status/823256735070744578">January 22, 2017</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>}, {
	<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Tasting tonight with @transmitterbrewing from 5 PM to 8 PM. Stop by and sample a Brett Saison and a Brett Stout! <a href="https://t.co/8fO8fRWEQV">pic.twitter.com/8fO8fRWEQV</a></p>&mdash; Brew (@BrewAlbany) <a href="https://twitter.com/BrewAlbany/status/821449984201658368">January 17, 2017</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
}, {
	<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">....and in addition to DANGEROUS PRESIDENT IPA being only $4 today in the taproom, you get $2… <a href="https://t.co/Fbzikna6QM">https://t.co/Fbzikna6QM</a></p>&mdash; KCBCbeer (@KCBCbeer) <a href="https://twitter.com/KCBCbeer/status/822899750093684737">January 21, 2017</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>}, {<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Trivia is back this Thursday night at <a href="https://twitter.com/LICbp">@LICbp</a> !! We open at 4pm. Trivia starts at 7:30pm. <a href="https://twitter.com/hashtag/trivia?src=hash">#trivia</a> <a href="https://twitter.com/hashtag/drinklocal?src=hash">#drinklocal</a> <a href="https://t.co/eK2fEDHOPV">pic.twitter.com/eK2fEDHOPV</a></p>&mdash; LIC Beer Project (@LICbp) <a href="https://twitter.com/LICbp/status/821201658994692096">January 17, 2017</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>}, {
	<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Can release in the Tasting Room! Bring The Noise DIPA and A NY Thing American Pale Ale- $16 / 4-pack Come get em! Open at 5pm w <a href="https://twitter.com/herosNYC">@herosNYC</a> ! <a href="https://t.co/gN0cC7ZP8Q">pic.twitter.com/gN0cC7ZP8Q</a></p>&mdash; Interboro (@InterboroNYC) <a href="https://twitter.com/InterboroNYC/status/822550575099289600">January 20, 2017</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
}, {
	<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/hashtag/HiFiRecords?src=hash">#HiFiRecords</a> returns with their Sunday Pop-Up! Every other Sunday 12-5<a href="https://twitter.com/hashtag/ShopLocal?src=hash">#ShopLocal</a> <a href="https://twitter.com/hashtag/BeerVinyl?src=hash">#BeerVinyl</a> <a href="https://t.co/FBrH7fGEKs">pic.twitter.com/FBrH7fGEKs</a></p>&mdash; SingleCut Beersmiths (@SingleCutBeer) <a href="https://twitter.com/SingleCutBeer/status/823233450132066304">January 22, 2017</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
}, {<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">To help take your mind off the unpleasantness. Vert Mont cans today at 5pm! <a href="https://twitter.com/hashtag/drinkawaythepain?src=hash">#drinkawaythepain</a> <a href="https://t.co/um1Ahx3SVR">https://t.co/um1Ahx3SVR</a></p>&mdash; GreenpointBeer (@GreenpointBeer) <a href="https://twitter.com/GreenpointBeer/status/822506541458673664">January 20, 2017</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>}]